// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type BoardDatum struct {
	ID    int32
	Name  string
	Value string
}

type Chat struct {
	ID        int32
	MemberID  int32
	Stamp     sql.NullTime
	Chat      sql.NullString
	ChatGroup sql.NullInt32
}

type ChatGroup struct {
	ID    int32
	Topic sql.NullString
}

type ChatGroupMember struct {
	GroupID  int32
	MemberID int32
}

type Favorite struct {
	ID       int32
	MemberID int32
	ThreadID int32
}

type Member struct {
	ID               int32
	Name             string
	Pass             string
	Secret           string
	Ip               pgtype.CIDR
	DateJoined       sql.NullTime
	DateFirstPost    sql.NullTime
	EmailSignup      string
	Postalcode       string
	TotalThreads     sql.NullInt32
	TotalThreadPosts sql.NullInt32
	LastView         sql.NullTime
	LastPost         sql.NullTime
	LastChat         sql.NullTime
	LastSearch       sql.NullTime
	Banned           sql.NullBool
	IsAdmin          sql.NullBool
	Cookie           sql.NullString
	Session          sql.NullString
}

type MemberIgnore struct {
	MemberID       sql.NullInt32
	IgnoreMemberID sql.NullInt32
}

type MemberLurkUnlock struct {
	ID        int32
	MemberID  int32
	CreatedAt time.Time
}

type MemberPref struct {
	ID       int32
	PrefID   int32
	MemberID int32
	Value    string
}

type Message struct {
	ID             int32
	MemberID       int32
	Subject        string
	FirstPostID    sql.NullInt32
	DatePosted     time.Time
	Posts          sql.NullInt32
	Views          sql.NullInt32
	LastMemberID   int32
	DateLastPosted time.Time
}

type MessageMember struct {
	MemberID      int32
	MessageID     int32
	DatePosted    sql.NullTime
	LastViewPosts int32
	Deleted       bool
}

type MessagePost struct {
	ID         int32
	MessageID  int32
	DatePosted sql.NullTime
	MemberID   int32
	MemberIp   pgtype.CIDR
	Body       sql.NullString
}

type MessageViewer struct {
	MemberID   sql.NullInt32
	MessageID  sql.NullInt32
	Dotted     sql.NullBool
	LastViewed sql.NullTime
	Undot      bool
}

type Pref struct {
	ID         int32
	PrefTypeID int32
	Name       string
	Display    string
	Profile    bool
	Session    bool
	Editable   bool
	Width      sql.NullInt32
	Ordering   sql.NullInt32
}

type PrefType struct {
	ID   int32
	Name string
}

type Theme struct {
	ID    int32
	Name  string
	Value sql.NullString
	Main  bool
}

type Thread struct {
	ID             int32
	MemberID       int32
	Subject        string
	DatePosted     time.Time
	FirstPostID    sql.NullInt32
	Posts          sql.NullInt32
	Views          sql.NullInt32
	Sticky         sql.NullBool
	Locked         sql.NullBool
	LastMemberID   int32
	DateLastPosted time.Time
	Indexed        bool
	Edited         bool
	Deleted        bool
	Legendary      bool
}

type ThreadMember struct {
	MemberID      int32
	ThreadID      int32
	Undot         bool
	Ignore        bool
	DatePosted    sql.NullTime
	LastViewPosts int32
}

type ThreadPost struct {
	ID             int32
	ThreadID       int32
	DatePosted     sql.NullTime
	MemberID       int32
	MemberIp       pgtype.CIDR
	Indexed        bool
	Edited         bool
	Deleted        bool
	Body           sql.NullString
	ThreadPosition pgtype.Numeric
}

type ThreadViewer struct {
	MemberID   sql.NullInt32
	ThreadID   sql.NullInt32
	Ignored    sql.NullBool
	Dotted     sql.NullBool
	LastViewed sql.NullTime
	Undot      bool
}
