// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"goBoard/internal/core/ports"
	"sync"
)

// Ensure, that AuthenticationRepoMock does implement ports.AuthenticationRepo.
// If this is not the case, regenerate this file with moq.
var _ ports.AuthenticationRepo = &AuthenticationRepoMock{}

// AuthenticationRepoMock is a mock implementation of ports.AuthenticationRepo.
//
//	func TestSomethingThatUsesAuthenticationRepo(t *testing.T) {
//
//		// make and configure a mocked ports.AuthenticationRepo
//		mockedAuthenticationRepo := &AuthenticationRepoMock{
//			AuthenticateFunc: func(username string, password string) (int, error) {
//				panic("mock out the Authenticate method")
//			},
//		}
//
//		// use mockedAuthenticationRepo in code that requires ports.AuthenticationRepo
//		// and then make assertions.
//
//	}
type AuthenticationRepoMock struct {
	// AuthenticateFunc mocks the Authenticate method.
	AuthenticateFunc func(username string, password string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Authenticate holds details about calls to the Authenticate method.
		Authenticate []struct {
			// Username is the username argument value.
			Username string
			// Password is the password argument value.
			Password string
		}
	}
	lockAuthenticate sync.RWMutex
}

// Authenticate calls AuthenticateFunc.
func (mock *AuthenticationRepoMock) Authenticate(username string, password string) (int, error) {
	if mock.AuthenticateFunc == nil {
		panic("AuthenticationRepoMock.AuthenticateFunc: method is nil but AuthenticationRepo.Authenticate was just called")
	}
	callInfo := struct {
		Username string
		Password string
	}{
		Username: username,
		Password: password,
	}
	mock.lockAuthenticate.Lock()
	mock.calls.Authenticate = append(mock.calls.Authenticate, callInfo)
	mock.lockAuthenticate.Unlock()
	return mock.AuthenticateFunc(username, password)
}

// AuthenticateCalls gets all the calls that were made to Authenticate.
// Check the length with:
//
//	len(mockedAuthenticationRepo.AuthenticateCalls())
func (mock *AuthenticationRepoMock) AuthenticateCalls() []struct {
	Username string
	Password string
} {
	var calls []struct {
		Username string
		Password string
	}
	mock.lockAuthenticate.RLock()
	calls = mock.calls.Authenticate
	mock.lockAuthenticate.RUnlock()
	return calls
}
