// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"goBoard/internal/core/domain"
	"goBoard/internal/core/ports"
	"sync"
)

// Ensure, that ThreadRepoMock does implement ports.ThreadRepo.
// If this is not the case, regenerate this file with moq.
var _ ports.ThreadRepo = &ThreadRepoMock{}

// ThreadRepoMock is a mock implementation of ports.ThreadRepo.
//
//	func TestSomethingThatUsesThreadRepo(t *testing.T) {
//
//		// make and configure a mocked ports.ThreadRepo
//		mockedThreadRepo := &ThreadRepoMock{
//			GetPostByIDFunc: func(id int) (*domain.Post, error) {
//				panic("mock out the GetPostByID method")
//			},
//			GetThreadByIDFunc: func(id int) (*domain.Thread, error) {
//				panic("mock out the GetThreadByID method")
//			},
//			ListPostsForThreadFunc: func(limit int, offset int, id int) ([]domain.Post, error) {
//				panic("mock out the ListPostsForThread method")
//			},
//			ListThreadsFunc: func(limit int, offset int) (*domain.SiteContext, error) {
//				panic("mock out the ListThreads method")
//			},
//			ListThreadsByMemberIDFunc: func(memberID int, limit int, offset int) ([]domain.Thread, error) {
//				panic("mock out the ListThreadsByMemberID method")
//			},
//			SavePostFunc: func(post domain.Post) (int, error) {
//				panic("mock out the SavePost method")
//			},
//			SaveThreadFunc: func(thread domain.Thread) (int, error) {
//				panic("mock out the SaveThread method")
//			},
//		}
//
//		// use mockedThreadRepo in code that requires ports.ThreadRepo
//		// and then make assertions.
//
//	}
type ThreadRepoMock struct {
	// GetPostByIDFunc mocks the GetPostByID method.
	GetPostByIDFunc func(id int) (*domain.Post, error)

	// GetThreadByIDFunc mocks the GetThreadByID method.
	GetThreadByIDFunc func(id int) (*domain.Thread, error)

	// ListPostsForThreadFunc mocks the ListPostsForThread method.
	ListPostsForThreadFunc func(limit int, offset int, id int) ([]domain.Post, error)

	// ListThreadsFunc mocks the ListThreads method.
	ListThreadsFunc func(limit int, offset int) (*domain.SiteContext, error)

	// ListThreadsByMemberIDFunc mocks the ListThreadsByMemberID method.
	ListThreadsByMemberIDFunc func(memberID int, limit int, offset int) ([]domain.Thread, error)

	// SavePostFunc mocks the SavePost method.
	SavePostFunc func(post domain.Post) (int, error)

	// SaveThreadFunc mocks the SaveThread method.
	SaveThreadFunc func(thread domain.Thread) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPostByID holds details about calls to the GetPostByID method.
		GetPostByID []struct {
			// ID is the id argument value.
			ID int
		}
		// GetThreadByID holds details about calls to the GetThreadByID method.
		GetThreadByID []struct {
			// ID is the id argument value.
			ID int
		}
		// ListPostsForThread holds details about calls to the ListPostsForThread method.
		ListPostsForThread []struct {
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
			// ID is the id argument value.
			ID int
		}
		// ListThreads holds details about calls to the ListThreads method.
		ListThreads []struct {
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// ListThreadsByMemberID holds details about calls to the ListThreadsByMemberID method.
		ListThreadsByMemberID []struct {
			// MemberID is the memberID argument value.
			MemberID int
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// SavePost holds details about calls to the SavePost method.
		SavePost []struct {
			// Post is the post argument value.
			Post domain.Post
		}
		// SaveThread holds details about calls to the SaveThread method.
		SaveThread []struct {
			// Thread is the thread argument value.
			Thread domain.Thread
		}
	}
	lockGetPostByID           sync.RWMutex
	lockGetThreadByID         sync.RWMutex
	lockListPostsForThread    sync.RWMutex
	lockListThreads           sync.RWMutex
	lockListThreadsByMemberID sync.RWMutex
	lockSavePost              sync.RWMutex
	lockSaveThread            sync.RWMutex
}

// GetPostByID calls GetPostByIDFunc.
func (mock *ThreadRepoMock) GetPostByID(id int) (*domain.Post, error) {
	if mock.GetPostByIDFunc == nil {
		panic("ThreadRepoMock.GetPostByIDFunc: method is nil but ThreadRepo.GetPostByID was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockGetPostByID.Lock()
	mock.calls.GetPostByID = append(mock.calls.GetPostByID, callInfo)
	mock.lockGetPostByID.Unlock()
	return mock.GetPostByIDFunc(id)
}

// GetPostByIDCalls gets all the calls that were made to GetPostByID.
// Check the length with:
//
//	len(mockedThreadRepo.GetPostByIDCalls())
func (mock *ThreadRepoMock) GetPostByIDCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockGetPostByID.RLock()
	calls = mock.calls.GetPostByID
	mock.lockGetPostByID.RUnlock()
	return calls
}

// GetThreadByID calls GetThreadByIDFunc.
func (mock *ThreadRepoMock) GetThreadByID(id int) (*domain.Thread, error) {
	if mock.GetThreadByIDFunc == nil {
		panic("ThreadRepoMock.GetThreadByIDFunc: method is nil but ThreadRepo.GetThreadByID was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockGetThreadByID.Lock()
	mock.calls.GetThreadByID = append(mock.calls.GetThreadByID, callInfo)
	mock.lockGetThreadByID.Unlock()
	return mock.GetThreadByIDFunc(id)
}

// GetThreadByIDCalls gets all the calls that were made to GetThreadByID.
// Check the length with:
//
//	len(mockedThreadRepo.GetThreadByIDCalls())
func (mock *ThreadRepoMock) GetThreadByIDCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockGetThreadByID.RLock()
	calls = mock.calls.GetThreadByID
	mock.lockGetThreadByID.RUnlock()
	return calls
}

// ListPostsForThread calls ListPostsForThreadFunc.
func (mock *ThreadRepoMock) ListPostsForThread(limit int, offset int, id int) ([]domain.Post, error) {
	if mock.ListPostsForThreadFunc == nil {
		panic("ThreadRepoMock.ListPostsForThreadFunc: method is nil but ThreadRepo.ListPostsForThread was just called")
	}
	callInfo := struct {
		Limit  int
		Offset int
		ID     int
	}{
		Limit:  limit,
		Offset: offset,
		ID:     id,
	}
	mock.lockListPostsForThread.Lock()
	mock.calls.ListPostsForThread = append(mock.calls.ListPostsForThread, callInfo)
	mock.lockListPostsForThread.Unlock()
	return mock.ListPostsForThreadFunc(limit, offset, id)
}

// ListPostsForThreadCalls gets all the calls that were made to ListPostsForThread.
// Check the length with:
//
//	len(mockedThreadRepo.ListPostsForThreadCalls())
func (mock *ThreadRepoMock) ListPostsForThreadCalls() []struct {
	Limit  int
	Offset int
	ID     int
} {
	var calls []struct {
		Limit  int
		Offset int
		ID     int
	}
	mock.lockListPostsForThread.RLock()
	calls = mock.calls.ListPostsForThread
	mock.lockListPostsForThread.RUnlock()
	return calls
}

// ListThreads calls ListThreadsFunc.
func (mock *ThreadRepoMock) ListThreads(limit int, offset int) (*domain.SiteContext, error) {
	if mock.ListThreadsFunc == nil {
		panic("ThreadRepoMock.ListThreadsFunc: method is nil but ThreadRepo.ListThreads was just called")
	}
	callInfo := struct {
		Limit  int
		Offset int
	}{
		Limit:  limit,
		Offset: offset,
	}
	mock.lockListThreads.Lock()
	mock.calls.ListThreads = append(mock.calls.ListThreads, callInfo)
	mock.lockListThreads.Unlock()
	return mock.ListThreadsFunc(limit, offset)
}

// ListThreadsCalls gets all the calls that were made to ListThreads.
// Check the length with:
//
//	len(mockedThreadRepo.ListThreadsCalls())
func (mock *ThreadRepoMock) ListThreadsCalls() []struct {
	Limit  int
	Offset int
} {
	var calls []struct {
		Limit  int
		Offset int
	}
	mock.lockListThreads.RLock()
	calls = mock.calls.ListThreads
	mock.lockListThreads.RUnlock()
	return calls
}

// ListThreadsByMemberID calls ListThreadsByMemberIDFunc.
func (mock *ThreadRepoMock) ListThreadsByMemberID(memberID int, limit int, offset int) ([]domain.Thread, error) {
	if mock.ListThreadsByMemberIDFunc == nil {
		panic("ThreadRepoMock.ListThreadsByMemberIDFunc: method is nil but ThreadRepo.ListThreadsByMemberID was just called")
	}
	callInfo := struct {
		MemberID int
		Limit    int
		Offset   int
	}{
		MemberID: memberID,
		Limit:    limit,
		Offset:   offset,
	}
	mock.lockListThreadsByMemberID.Lock()
	mock.calls.ListThreadsByMemberID = append(mock.calls.ListThreadsByMemberID, callInfo)
	mock.lockListThreadsByMemberID.Unlock()
	return mock.ListThreadsByMemberIDFunc(memberID, limit, offset)
}

// ListThreadsByMemberIDCalls gets all the calls that were made to ListThreadsByMemberID.
// Check the length with:
//
//	len(mockedThreadRepo.ListThreadsByMemberIDCalls())
func (mock *ThreadRepoMock) ListThreadsByMemberIDCalls() []struct {
	MemberID int
	Limit    int
	Offset   int
} {
	var calls []struct {
		MemberID int
		Limit    int
		Offset   int
	}
	mock.lockListThreadsByMemberID.RLock()
	calls = mock.calls.ListThreadsByMemberID
	mock.lockListThreadsByMemberID.RUnlock()
	return calls
}

// SavePost calls SavePostFunc.
func (mock *ThreadRepoMock) SavePost(post domain.Post) (int, error) {
	if mock.SavePostFunc == nil {
		panic("ThreadRepoMock.SavePostFunc: method is nil but ThreadRepo.SavePost was just called")
	}
	callInfo := struct {
		Post domain.Post
	}{
		Post: post,
	}
	mock.lockSavePost.Lock()
	mock.calls.SavePost = append(mock.calls.SavePost, callInfo)
	mock.lockSavePost.Unlock()
	return mock.SavePostFunc(post)
}

// SavePostCalls gets all the calls that were made to SavePost.
// Check the length with:
//
//	len(mockedThreadRepo.SavePostCalls())
func (mock *ThreadRepoMock) SavePostCalls() []struct {
	Post domain.Post
} {
	var calls []struct {
		Post domain.Post
	}
	mock.lockSavePost.RLock()
	calls = mock.calls.SavePost
	mock.lockSavePost.RUnlock()
	return calls
}

// SaveThread calls SaveThreadFunc.
func (mock *ThreadRepoMock) SaveThread(thread domain.Thread) (int, error) {
	if mock.SaveThreadFunc == nil {
		panic("ThreadRepoMock.SaveThreadFunc: method is nil but ThreadRepo.SaveThread was just called")
	}
	callInfo := struct {
		Thread domain.Thread
	}{
		Thread: thread,
	}
	mock.lockSaveThread.Lock()
	mock.calls.SaveThread = append(mock.calls.SaveThread, callInfo)
	mock.lockSaveThread.Unlock()
	return mock.SaveThreadFunc(thread)
}

// SaveThreadCalls gets all the calls that were made to SaveThread.
// Check the length with:
//
//	len(mockedThreadRepo.SaveThreadCalls())
func (mock *ThreadRepoMock) SaveThreadCalls() []struct {
	Thread domain.Thread
} {
	var calls []struct {
		Thread domain.Thread
	}
	mock.lockSaveThread.RLock()
	calls = mock.calls.SaveThread
	mock.lockSaveThread.RUnlock()
	return calls
}
